<?php

namespace App\Http\Requests\acl\permissions;

use Illuminate\Foundation\Http\FormRequest;

class PermissionCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'title' => 'required|unique:permissions'
        ];
    }

    protected function prepareForValidation()
    {
        $this->merge([
            'title' =>  $this->permission
        ]);
    }

    public function messages()
    {
        return [
            'title.required' =>  'The permission field is required',
            'title.unique'  => 'The permission has already been there.'
        ]; // TODO: Change the autogenerated stub
    }
}
